---
- name: Update packages on Armbian hosts
  hosts: all
  tasks:
    # Update and install the base software
    - name: Update apt package cache.
      apt:
        update_cache: yes
        cache_valid_time: 600

    - name: Upgrade installed apt packages.
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        #register: upgrade

    - name: Ensure that a base set of software packages are installed.
      apt:
        name:
         - duf
         - needrestart
         - htop
        state: latest

    - name: Check if a new kernel is available
      ansible.builtin.command: needrestart -k -p > /dev/null; echo $?
      register: result
      ignore_errors: yes

    - name: No new kernel
      ansible.builtin.command: uname -r
      when: result.rc == 0

    - name: Restart the server if new kernel is available
      ansible.builtin.command: reboot
      when: result.rc == 2
      async: 1
      poll: 0

    - name: Wait for the reboot and reconnect
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
        timeout: 60
      connection: local

    - name: Check the Uptime of the servers
      shell: "uptime"
      register: Uptime

    - debug: var=Uptime.stdout
